### ISSUE TITLE
Any advise on printing these large components

### ISSUE THREAD

**Issue by AnykeyNL** [BCN3D/BCN3D-Moveo#12]
Hi, I just bought a sigma to print these things. Is there any advise on printer settings for especially these large components? Like layer height, infill and material choice?

Regards,
Richard

**Comment by kitusmark** [comment]
Hi @AnykeyNL !

Hope you like our Robotic Arm design and the BCN3D Sigma. I think it's better to open a post on the forum as you will be getting more feedback than here. 

https://www.bcn3dtechnologies.com/es/forums/

Thanks and have fun!

**Comment by AnykeyNL** [comment]
Thanks, I guess I was blind yesterday as I did look at the forum, but did not see a Moveo section.
