### ISSUE TITLE
Do we should pay for the wiring diagram?

### ISSUE THREAD

**Issue by AlexanderZhang11** [BCN3D/BCN3D-Moveo#13]
I cannot find the wiring diagram in the resource list. I am puzzled by the problem of wiring. So does it mean we should pay for this diagram?

**Comment by MarcusWolschon** [comment]
Is this a duplicate of
Wiring Diamgram is missed #6
?

**Comment by kitusmark** [comment]
Duplicate on #6

**Comment by MohammedAhamed** [comment]
I run the project  as graduation project  with some modifications   if any one want help   connect to me  for free  by email  mo.ah.has2014@gmail.com
