### ISSUE TITLE
"T" parts are missing

### ISSUE THREAD

**Issue by laovorak** [BCN3D/BCN3D-Moveo#5]
There is no T2M1D, T2M1I, T3M1, T4M1 in the STL section.

**Comment by jamesarm97** [comment]
This was already discusses. Not sure why when I look at my pull request it shows 0 additions and 0 deletions yet it has files attached. Has someone committed/ approved the pullnrequest yet?

https://github.com/BCN3D/BCN3D-Moveo/pull/4/files

**Comment by kitusmark** [comment]
@laovorak Merged! Sync your repos and the parts should show up. 
Thanks @jamesarm97 :+1:
