### ISSUE TITLE
Igus rails in BoM -- are these needed?

### ISSUE THREAD

**Issue by dtmille2** [BCN3D/BCN3D-Moveo#9]
The following parts are listed in the BoM's but not shown in the instruction manual or the CAD assembly:

LINEAL GUIDES IGUS-WSQ_06-134mm
LINEAL GUIDES IGUS-WSQ_06-114mm
LINEAL GUIDES IGUS-WSQ_06-080mm

Am I missing something or are these not needed?

Thanks!!

**Comment by ShopMonkey** [comment]
I'm using regular 8mm rod (shafting) I don't see the need for lineal guides. They are in fact joint axles. Don't skimp on the bearings. I bought some cheep ones and they are unusable.

**Comment by kitusmark** [comment]
Hi @dtmille2 and @ShopMonkey 

We've updated the BOM file. Please take a look and get back to me.

https://github.com/BCN3D/BCN3D-Moveo/commit/0866a92501277636f76000a195d8a16d44b5b476

Thanks for the feedback!

**Comment by dtmille2** [comment]
Thanks for updating the BoM, the additional stepper motor part numbers are great.

Unfortunately items 12, 13, and 14 are still not fully defined -- it looks like these parts should be 8 mm diameter from the SolidWorks assembly.  Can you please confirm by updating the BoM? 

![image](https://cloud.githubusercontent.com/assets/2092921/19629971/0bc39ff8-994e-11e6-90b4-f32fc33878b7.png)
